---
title: "Licitações e empenhos"
output:
    html_document:
    df_print: paged
theme: sandstone
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(here)
library(hrbrthemes)
theme_set(theme_ipsum_rc())

knitr::opts_chunk$set(tidy = FALSE,
                      fig.width = 6,
                      fig.height = 4,
                      echo = FALSE)

paleta = c("#404E4D",
           "#92DCE5",
           "#938BA1",
           "#2D3142",
           "#F4743B")
```

```{r read}
lics = read_csv(
    here::here("data/ready/licitacoes-portal.csv"),
    col_types = cols(
        .default = col_character(),
        valor_licitacao = col_double(),
        data_resultado_compra = col_date(),
        data_abertura = col_date()
    )
)

empsrel = read_csv(
    here::here("data/ready/empenhosrelacionados-portal.csv"),
    col_types = cols(
        .default = col_character(),
        data_emissao_empenho = col_date(),
        valor_empenho_r = col_double()
    )
)
```



```{r}
# Apenas órgão superiores federais
lics_f = lics %>% 
    filter(as.numeric(codigo_orgao_superior) %% 1000 == 0, 
           as.numeric(codigo_orgao_superior) > 2e4, as.numeric(codigo_orgao_superior) < 9e4)
```

```{r}
les =  lics_f %>% left_join(
    empsrel,
    by = c(
        "numero_licitacao",
        "codigo_ug",
        "nome_ug",
        "codigo_modalidade_compra",
        "modalidade_compra",
        "numero_processo"
    )
)

com_empenho = les %>%
    mutate(ano = str_sub(arquivo.x, 1, 4), 
           mes = str_sub(arquivo.x, 5, 6)) %>% 
    group_by(numero_licitacao, modalidade_compra, arquivo.x, situacao_licitacao, mes, ano) %>%
    summarise(tem_empenho = if_else(any(!is.na(codigo_empenho)), "Sim", "Não"),
              .groups = "drop") %>%
    count(modalidade_compra, tem_empenho, mes, ano, situacao_licitacao)

com_empenho %>%
    filter(situacao_licitacao %in% c("Encerrado", 
                                     "Publicado", 
                                     "Evento de Resultado de Julgame"), 
           (grepl("Pregão|Licitação", modalidade_compra))) %>%
    ggplot(aes(x = reorder(modalidade_compra, n), y = n, fill = tem_empenho)) +
    facet_grid(mes ~ ano) +
    geom_col() +
    scale_fill_manual(values = c("brown", "gray")) +
    coord_flip() + 
    labs(x = "", y = "Número de licitações", fill = "Tem empenho associado?", 
         title = "Licitações sem empenhos no Portal", 
         subtitle = "Modalidades mais comuns, situação encerrado, publicado ou com evento de julgamento")

ggsave("empenhos-modalidade.png", height = 10, width = 10)
```

```{r}
com_empenho %>%
    filter(situacao_licitacao %in% c("Encerrado", 
                                     "Publicado", 
                                     "Evento de Resultado de Julgame"), 
           (grepl("Pregão|Licitação", modalidade_compra))) %>%
    ggplot(aes(x = reorder(modalidade_compra, n), y = n, fill = tem_empenho)) +
    facet_grid(mes ~ ano) +
    geom_col() +
    scale_fill_manual(values = c("brown", "gray")) +
    coord_flip() + 
    labs(x = "", y = "Número de licitações", fill = "Tem empenho associado?")

ggsave("empenhos-junto.png", height = 8, width = 9)
```



```{r read}
empenhos = read_csv(here::here("data/raw/despesa_empenho.csv.gz"))
```